// Metadata for Arabic
const arMain = {
  title: "حسونة",
  description:
    "إبراهيم حسونة، مطور واجهات أمامية ومبرمج ويب متخصص في تطوير مواقع عالية الأداء باستخدام Next.js و React. أقدم حلول برمجية احترافية، بما في ذلك تطوير المتاجر الإلكترونية، تحسين محركات البحث (SEO)، وتصميم مواقع إلكترونية متجاوبة بأسعار تنافسية.",
  keywords: [
    "مبرمج مصري",
    "إبراهيم حسونة",
    "إبراهيم حسونة الهاشمي",
    "مطور ويب",
    "تصميم مواقع إلكترونية",
    "مطور Next.js",
    "تطوير مواقع الإنترنت",
    "مبرمج ويب محترف",
    "ابراهيم محمد حسونه",
    "تصميم وتطوير المواقع",
    "مبرمج Next.js في مصر",
    "إنشاء مواقع إلكترونية احترافية",
    "خدمات برمجة المواقع",
    "تطوير مواقع React و Next.js",
    "تحسين أداء المواقع",
    "مبرمج واجهات أمامية",
    "مطور مواقع سريع الاستجابة",
    "مبرمج متاجر إلكترونية",
    "مبرمج SEO",
    "مطور مواقع متعدد اللغات",
    "تحسين محركات البحث",
    "خبير برمجة الويب",
    "إنشاء متاجر إلكترونية",
    "تصميم مواقع متجاوبة",
    "مطور JavaScript و React",
  ],
};
export const arMetadata = {
  metadataBase: new URL("https://hassouna.vercel.app"),
  title: {
    template: `%s - ${arMain.title}`,
    default: `${arMain.title} - الابداع التقنى`,
  },
  description: arMain.description,
  charset: "UTF-8",
  robots: "index, follow",
  keywords: arMain.keywords,
  openGraph: {
    title: arMain.title,
    description: arMain.description,
    type: "website",
    url: `https://hassouna.vercel.app/ar`,
    images: process.env.NEXT_IMAGE_META,
  },
  twitter: {
    card: "summary_large_image",
    title: arMain.title,
    description: arMain.description,
    images: process.env.NEXT_IMAGE_META,
  },
};

// Metadata for English
const enMain = {
  title: "Hassouna",
  description:
    "Ibrahim Hassouna, a frontend developer and web programmer specializing in high-performance websites using Next.js and React. I provide professional web solutions, including e-commerce development, SEO optimization, and responsive website design at competitive prices.",
  keywords: [
    "Egyptian Web Developer",
    "Ibrahim Hassouna",
    "Ibrahim Hassouna Al-Hashimi",
    "Web Developer",
    "Website Design",
    "Next.js Developer",
    "Web Development",
    "Professional Web Programmer",
    "Ibrahim Mohamed Hassouna",
    "Website Design & Development",
    "Next.js Developer in Egypt",
    "Professional Website Creation",
    "Web Programming Services",
    "React & Next.js Development",
    "Website Performance Optimization",
    "Frontend Developer",
    "Responsive Web Developer",
    "E-commerce Developer",
    "SEO Developer",
    "Multilingual Website Developer",
    "Search Engine Optimization",
    "Web Development Expert",
    "E-commerce Website Creation",
    "Responsive Website Design",
    "JavaScript & React Developer",
  ],
};
export const enMetadata = {
  metadataBase: new URL("https://hassouna.vercel.app"),
  title: {
    template: `%s - ${enMain.title}`,
    default: `${enMain.title} - Technical Creativity`,
  },
  description: enMain.description,
  charset: "UTF-8",
  robots: "index, follow",
  keywords: enMain.keywords,
  openGraph: {
    title: enMain.title,
    description: enMain.description,
    type: "website",
    url: "https://hassouna.vercel.app/en",
    images: process.env.NEXT_IMAGE_META,
  },
  twitter: {
    card: "summary_large_image",
    title: enMain.title,
    description: enMain.description,
    images: process.env.NEXT_IMAGE_META,
  },
};
